"""new columns request

Revision ID: 1472abe98578
Revises: cfc6349787ac
Create Date: 2026-04-01 21:22:28.193189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1472abe98578'
down_revision = 'cfc6349787ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  

    with op.batch_alter_table('resource_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reminder_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reminder_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_requests', schema=None) as batch_op:
        batch_op.drop_column('reminder_count')
        batch_op.drop_column('last_reminder_sent')



    # ### end Alembic commands ###
