"""add columns communucation UTA

Revision ID: 1b5ed41ec92f
Revises: d0edd1895dae
Create Date: 2026-05-07 23:34:17.264401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5ed41ec92f'
down_revision = 'd0edd1895dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_to_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_message_reply_to', ['reply_to_id'], unique=False)
        batch_op.create_foreign_key("reply_to_id", 'chat_messages', ['reply_to_id'], ['id'])

    with op.batch_alter_table('project_chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_chat_activity', ['activity_id'], unique=False)
        batch_op.create_foreign_key("activity_id", 'activities', ['activity_id'], ['id'])

    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('project_chats', schema=None) as batch_op:
        batch_op.drop_constraint("activity_id", type_='foreignkey')
        batch_op.drop_index('idx_chat_activity')
        batch_op.drop_column('activity_id')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint("reply_to_id", type_='foreignkey')
        batch_op.drop_index('idx_message_reply_to')
        batch_op.drop_column('reply_to_id')

    # ### end Alembic commands ###
