"""add table projectlog

Revision ID: 2690f7584402
Revises: 4e8a7be99924
Create Date: 2026-03-27 02:51:52.436249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2690f7584402'
down_revision = '4e8a7be99924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_progress_project', ['project_id'], unique=False)


    # ### end Alembic commands ###


def downgrade():


    with op.batch_alter_table('project_progress', schema=None) as batch_op:
        batch_op.drop_index('idx_progress_project')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
