"""delete index resourc

Revision ID: 2dd6e35469b2
Revises: 4ba536acca18
Create Date: 2026-03-24 20:51:23.505874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd6e35469b2'
down_revision = '4ba536acca18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('resource_deliveries', schema=None) as batch_op:
        batch_op.drop_constraint('uq_delivery_number', type_='unique')

    with op.batch_alter_table('resource_request_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_req_item', type_='unique')

    with op.batch_alter_table('resource_requests', schema=None) as batch_op:
        batch_op.drop_constraint('uq_resource_request_project_supplier', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_requests', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_resource_request_project_supplier', ['project_id', 'supplier_id'])

    with op.batch_alter_table('resource_request_items', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_req_item', ['request_id', 'resource_id'])

    with op.batch_alter_table('resource_deliveries', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_delivery_number', ['request_id', 'delivery_number'])


    # ### end Alembic commands ###
