"""add column ratetype

Revision ID: 31b8ce8face7
Revises: f79962aab126
Create Date: 2026-03-22 23:45:28.993396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b8ce8face7'
down_revision = 'f79962aab126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_type', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_resources', schema=None) as batch_op:
        batch_op.drop_column('rate_type')

    # ### end Alembic commands ###
