"""add column base_currency

Revision ID: 458297c4917b
Revises: 
Create Date: 2026-03-17 01:19:14.410129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458297c4917b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_currency', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('base_currency')

    # ### end Alembic commands ###
