"""delete index

Revision ID: 4ba536acca18
Revises: 920a7f7151e8
Create Date: 2026-03-24 20:11:32.115033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba536acca18'
down_revision = '920a7f7151e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_resources', schema=None) as batch_op:
        batch_op.drop_constraint('uq_activity_resource', type_='unique')

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('activity_resources', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_activity_resource', ['activity_id', 'resource_id'])

    # ### end Alembic commands ###
