"""add cost columns activ wbs

Revision ID: 4e8a7be99924
Revises: 688a9affa933
Create Date: 2026-03-26 23:45:23.686220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8a7be99924'
down_revision = '688a9affa933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planned_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('remaining_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cost_variance', sa.Float(), nullable=True))

   

    with op.batch_alter_table('task_execution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planned_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('actual_cost', sa.Float(), nullable=True))

    with op.batch_alter_table('wbs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_variance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wbs', schema=None) as batch_op:
        batch_op.drop_column('cost_variance')

    with op.batch_alter_table('task_execution', schema=None) as batch_op:
        batch_op.drop_column('actual_cost')
        batch_op.drop_column('planned_cost')



    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('cost_variance')
        batch_op.drop_column('remaining_cost')
        batch_op.drop_column('planned_cost')

    # ### end Alembic commands ###
