"""userss new columns

Revision ID: 5e1a03ee80ec
Revises: e300de5e1f77
Create Date: 2026-05-01 01:32:23.297909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1a03ee80ec'
down_revision = 'e300de5e1f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('task_reminders', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('daily_digest', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sidebar_collapsed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sidebar_collapsed')
        batch_op.drop_column('theme')
        batch_op.drop_column('daily_digest')
        batch_op.drop_column('task_reminders')
        batch_op.drop_column('push_notifications')
        batch_op.drop_column('email_notifications')

   
    # ### end Alembic commands ###
