"""add relationship notification

Revision ID: 688a9affa933
Revises: 2dd6e35469b2
Create Date: 2026-03-24 23:31:56.337998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688a9affa933'
down_revision = '2dd6e35469b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_delivery_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('related_request_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("related_request_id", 'resource_requests', ['related_request_id'], ['id'])
        batch_op.create_foreign_key("related_delivery_id", 'resource_deliveries', ['related_delivery_id'], ['id'])



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint("related_request_id", type_='foreignkey')
        batch_op.drop_constraint("related_delivery_id", type_='foreignkey')
        batch_op.drop_column('related_request_id')
        batch_op.drop_column('related_delivery_id')

    # ### end Alembic commands ###
