"""add codes tables

Revision ID: 762ab5be5ab1
Revises: e1e3fa7635ff
Create Date: 2026-03-18 00:56:53.382007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762ab5be5ab1'
down_revision = 'e1e3fa7635ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_codes', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_code_org')
        batch_op.drop_index('idx_activity_code_scope')
        batch_op.drop_index('idx_activity_code_type')

    op.drop_table('activity_codes')
    with op.batch_alter_table('project_codes', schema=None) as batch_op:
        batch_op.drop_index('idx_code_project')
        batch_op.drop_index('idx_code_type')

    op.drop_table('project_codes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_codes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('code_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('code_value', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code_type', name='uq_project_code_type')
    )
    with op.batch_alter_table('project_codes', schema=None) as batch_op:
        batch_op.create_index('idx_code_type', ['code_type'], unique=False)
        batch_op.create_index('idx_code_project', ['project_id'], unique=False)

    op.create_table('activity_codes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('org_id', sa.INTEGER(), nullable=False),
    sa.Column('code_scope', sa.VARCHAR(length=50), nullable=True),
    sa.Column('code_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('code_value', sa.VARCHAR(length=50), nullable=False),
    sa.Column('code_description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('code_color', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('activity_codes', schema=None) as batch_op:
        batch_op.create_index('idx_activity_code_type', ['code_type'], unique=False)
        batch_op.create_index('idx_activity_code_scope', ['code_scope'], unique=False)
        batch_op.create_index('idx_activity_code_org', ['org_id'], unique=False)

    # ### end Alembic commands ###
