"""add new table for recource

Revision ID: 916215142fa7
Revises: 762ab5be5ab1
Create Date: 2026-03-20 22:12:26.372912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916215142fa7'
down_revision = '762ab5be5ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("created_by", 'users', ['created_by'], ['id'])

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimum_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('maximum_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('attributes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), nullable=True))
        batch_op.create_index('idx_resource_active', ['is_active'], unique=False)

    with op.batch_alter_table('task_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_resource_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planned_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('actual_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('remaining_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('planned_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('actual_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('allocation_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('planned_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('planned_finish', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_finish', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_index('idx_task_res_activity', ['activity_resource_id'], unique=False)
        batch_op.create_index('idx_task_res_resource', ['resource_id'], unique=False)
        batch_op.create_index('idx_task_res_task', ['task_id'], unique=False)
        batch_op.create_unique_constraint('uq_task_resource', ['task_id', 'resource_id'])
        batch_op.create_foreign_key("created_by", 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key("activity_resource_id", 'activity_resources', ['activity_resource_id'], ['id'])
        batch_op.drop_column('resource_name')
        batch_op.drop_column('quantity')
        batch_op.drop_column('resource_type')
        batch_op.drop_column('cost')
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('resource_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('resource_name', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint("activity_resource_id", type_='foreignkey')
        batch_op.drop_constraint("created_by", type_='foreignkey')
        batch_op.drop_constraint('uq_task_resource', type_='unique')
        batch_op.drop_index('idx_task_res_task')
        batch_op.drop_index('idx_task_res_resource')
        batch_op.drop_index('idx_task_res_activity')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('actual_finish')
        batch_op.drop_column('actual_start')
        batch_op.drop_column('planned_finish')
        batch_op.drop_column('planned_start')
        batch_op.drop_column('allocation_percentage')
        batch_op.drop_column('actual_cost')
        batch_op.drop_column('planned_cost')
        batch_op.drop_column('remaining_quantity')
        batch_op.drop_column('actual_quantity')
        batch_op.drop_column('planned_quantity')
        batch_op.drop_column('activity_resource_id')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index('idx_resource_active')
        batch_op.drop_column('is_shared')
        batch_op.drop_column('attributes')
        batch_op.drop_column('maximum_quantity')
        batch_op.drop_column('minimum_quantity')

    with op.batch_alter_table('activity_resources', schema=None) as batch_op:
        batch_op.drop_constraint("created_by", type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('is_approved')
        batch_op.drop_column('remaining_cost')

    # ### end Alembic commands ###
