"""note columns

Revision ID: caf3e4fe81eb
Revises: 1472abe98578
Create Date: 2026-04-02 01:42:59.488478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf3e4fe81eb'
down_revision = '1472abe98578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('resource_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_deliveries', schema=None) as batch_op:
        batch_op.drop_column('notes')

    
    # ### end Alembic commands ###
