"""add new columns and table resuorce

Revision ID: cfc6349787ac
Revises: 2690f7584402
Create Date: 2026-04-01 00:14:01.208796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'cfc6349787ac'
down_revision = '2690f7584402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_activities')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verification_notes')
        batch_op.drop_column('verified_by')
        batch_op.drop_column('verification_required')

    with op.batch_alter_table('activity_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('file_extension', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('file_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('source_task_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approval_notes', sa.Text(), nullable=True))
        batch_op.create_index('idx_document_task', ['source_task_id'], unique=False)
        batch_op.create_foreign_key("source_task_id", 'tasks', ['source_task_id'], ['id'])

    with op.batch_alter_table('project_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_extension', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=1000), nullable=True))

   
    with op.batch_alter_table('resource_request_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('offer_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('offer_currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('offer_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('offer_submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('offer_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_constraint('employee_id', type_='foreignkey')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('supervisor_approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('supervisor_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delegate_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delegate_confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delegate_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('completion_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('completion_status')
        batch_op.drop_column('delegate_notes')
        batch_op.drop_column('delegate_confirmed_at')
        batch_op.drop_column('delegate_confirmed')
        batch_op.drop_column('supervisor_notes')
        batch_op.drop_column('supervisor_approved_at')
        batch_op.drop_column('supervisor_approved')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('employee_id', 'users', ['employee_id'], ['id'])

    with op.batch_alter_table('resource_request_items', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('total_price')
        batch_op.drop_column('unit_price')
        batch_op.drop_column('offer_status')
        batch_op.drop_column('offer_submitted_at')
        batch_op.drop_column('offer_notes')
        batch_op.drop_column('offer_currency')
        batch_op.drop_column('offer_price')
        batch_op.drop_column('resource_code')


    with op.batch_alter_table('project_documents', schema=None) as batch_op:
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_extension')

    with op.batch_alter_table('activity_documents', schema=None) as batch_op:
        batch_op.drop_constraint("source_task_id", type_='foreignkey')
        batch_op.drop_index('idx_document_task')
        batch_op.drop_column('approval_notes')
        batch_op.drop_column('source_task_id')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('file_url')
        batch_op.drop_column('file_path')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('file_extension')
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_size')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_required', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('verified_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('verification_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DATETIME(), nullable=True))

    op.create_table('_alembic_tmp_activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('wbs_id', sa.INTEGER(), nullable=True),
    sa.Column('calendar_id', sa.INTEGER(), nullable=True),
    sa.Column('activity_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('activity_code', sa.VARCHAR(length=100), nullable=True),
    sa.Column('activity_name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('instructions', sa.TEXT(), nullable=True),
    sa.Column('activity_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('original_duration', sa.FLOAT(), nullable=True),
    sa.Column('remaining_duration', sa.FLOAT(), nullable=True),
    sa.Column('actual_duration', sa.FLOAT(), nullable=True),
    sa.Column('at_complete_duration', sa.FLOAT(), nullable=True),
    sa.Column('budgeted_units', sa.FLOAT(), nullable=True),
    sa.Column('actual_units', sa.FLOAT(), nullable=True),
    sa.Column('remaining_units', sa.FLOAT(), nullable=True),
    sa.Column('at_complete_units', sa.FLOAT(), nullable=True),
    sa.Column('planned_start', sa.DATETIME(), nullable=True),
    sa.Column('planned_finish', sa.DATETIME(), nullable=True),
    sa.Column('early_start', sa.DATETIME(), nullable=True),
    sa.Column('early_finish', sa.DATETIME(), nullable=True),
    sa.Column('late_start', sa.DATETIME(), nullable=True),
    sa.Column('late_finish', sa.DATETIME(), nullable=True),
    sa.Column('actual_start', sa.DATETIME(), nullable=True),
    sa.Column('actual_finish', sa.DATETIME(), nullable=True),
    sa.Column('progress_percentage', sa.FLOAT(), nullable=True),
    sa.Column('physical_complete', sa.FLOAT(), nullable=True),
    sa.Column('duration_percent_complete', sa.FLOAT(), nullable=True),
    sa.Column('total_float', sa.FLOAT(), nullable=True),
    sa.Column('free_float', sa.FLOAT(), nullable=True),
    sa.Column('float_path', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('difficulty_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('supervisor_id', sa.INTEGER(), nullable=True),
    sa.Column('delegate_id', sa.INTEGER(), nullable=True),
    sa.Column('responsible_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('activity_code_values', sqlite.JSON(), nullable=True),
    sa.Column('udf_values', sqlite.JSON(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.Column('completion_quality', sa.VARCHAR(length=20), nullable=True),
    sa.Column('location', sa.VARCHAR(length=500), nullable=True),
    sa.Column('coordinates', sa.VARCHAR(length=100), nullable=True),
    sa.Column('primary_constraint', sa.VARCHAR(length=50), nullable=True),
    sa.Column('primary_constraint_date', sa.DATETIME(), nullable=True),
    sa.Column('secondary_constraint', sa.VARCHAR(length=50), nullable=True),
    sa.Column('secondary_constraint_date', sa.DATETIME(), nullable=True),
    sa.Column('must_finish_by', sa.DATETIME(), nullable=True),
    sa.Column('earned_value', sa.FLOAT(), nullable=True),
    sa.Column('planned_value', sa.FLOAT(), nullable=True),
    sa.Column('actual_cost', sa.FLOAT(), nullable=True),
    sa.Column('cpi', sa.FLOAT(), nullable=True),
    sa.Column('spi', sa.FLOAT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('is_criticall', sa.BOOLEAN(), nullable=True),
    sa.Column('planned_cost', sa.FLOAT(), nullable=True),
    sa.Column('remaining_cost', sa.FLOAT(), nullable=True),
    sa.Column('cost_variance', sa.FLOAT(), nullable=True),
    sa.CheckConstraint('progress_percentage >= 0 AND progress_percentage <= 100', name='chk_activity_progress'),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delegate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wbs_id'], ['wbs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'activity_id', name='uq_activity_id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###
