"""add new columns communcation

Revision ID: d0edd1895dae
Revises: 5e1a03ee80ec
Create Date: 2026-05-05 23:09:29.230414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0edd1895dae'
down_revision = '5e1a03ee80ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mime_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('file_extension', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('image_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_thumbnail', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('processing_status', sa.String(length=20), nullable=True))
        batch_op.create_index('idx_attachment_file_type', ['file_type'], unique=False)

  
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index('idx_attachment_file_type')
        batch_op.drop_column('processing_status')
        batch_op.drop_column('video_thumbnail')
        batch_op.drop_column('video_duration')
        batch_op.drop_column('image_height')
        batch_op.drop_column('image_width')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_extension')
        batch_op.drop_column('mime_type')

    # ### end Alembic commands ###
