"""add ai table

Revision ID: e1e3fa7635ff
Revises: 458297c4917b
Create Date: 2026-03-17 04:00:13.777529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e1e3fa7635ff'
down_revision = '458297c4917b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_ai_command_results')
    with op.batch_alter_table('ai_command_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.drop_index('idx_ai_result_command')
        batch_op.drop_index('idx_ai_result_type')
        batch_op.drop_column('chart_data')
        batch_op.drop_column('report_data')
        batch_op.drop_column('action_type')
        batch_op.drop_column('data')
        batch_op.drop_column('affected_ids')
        batch_op.drop_column('affected_count')
        batch_op.drop_column('summary')

    with op.batch_alter_table('ai_commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('command_language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('processing_notes', sa.Text(), nullable=True))
        batch_op.drop_index('idx_ai_command_target')
        batch_op.drop_column('result_stats')
        batch_op.drop_column('has_attachments')
        batch_op.drop_column('tokens_used')
        batch_op.drop_column('error_message')
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('attachments_count')

    with op.batch_alter_table('ai_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_name_ar', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('report_name_en', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('report_summary_ar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('report_summary_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recommendations', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('parameters', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('filters', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('sort_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('group_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('chart_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('chart_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('export_formats', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_exported_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('display_config')

    with op.batch_alter_table('ai_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_ar', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('description_ar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('related_resource_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('potential_impact', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.drop_index('idx_ai_suggestion_project')
        batch_op.drop_index('idx_ai_suggestion_status')
        # batch_op.drop_constraint("implemented_by", type_='foreignkey')
        batch_op.create_foreign_key("related_resource_id", 'resources', ['related_resource_id'], ['id'])
        batch_op.drop_column('potential_delay_reduction')
        batch_op.drop_column('category')
        batch_op.drop_column('potential_savings')
        batch_op.drop_column('reasoning')
        batch_op.drop_column('confidence')
        batch_op.drop_column('created_by')
        batch_op.drop_column('expected_impact')
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('expected_impact', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('reasoning', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('potential_savings', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('potential_delay_reduction', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint("related_resource_id", type_='foreignkey')
        # batch_op.create_foreign_key("implemented_by", 'users', ['created_by'], ['id'])
        batch_op.create_index('idx_ai_suggestion_status', ['status'], unique=False)
        batch_op.create_index('idx_ai_suggestion_project', ['related_project_id'], unique=False)
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('potential_impact')
        batch_op.drop_column('related_resource_id')
        batch_op.drop_column('description_en')
        batch_op.drop_column('description_ar')
        batch_op.drop_column('title_en')
        batch_op.drop_column('title_ar')

    with op.batch_alter_table('ai_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_config', sqlite.JSON(), nullable=True))
        batch_op.drop_column('last_exported_at')
        batch_op.drop_column('export_formats')
        batch_op.drop_column('chart_type')
        batch_op.drop_column('chart_data')
        batch_op.drop_column('group_by')
        batch_op.drop_column('sort_by')
        batch_op.drop_column('filters')
        batch_op.drop_column('parameters')
        batch_op.drop_column('recommendations')
        batch_op.drop_column('report_summary_en')
        batch_op.drop_column('report_summary_ar')
        batch_op.drop_column('report_name_en')
        batch_op.drop_column('report_name_ar')

    with op.batch_alter_table('ai_commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachments_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('estimated_cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('tokens_used', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('has_attachments', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('result_stats', sqlite.JSON(), nullable=True))
        batch_op.create_index('idx_ai_command_target', ['target_type'], unique=False)
        batch_op.drop_column('processing_notes')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('command_language')

    with op.batch_alter_table('ai_command_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('affected_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('affected_ids', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('data', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('action_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('report_data', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('chart_data', sqlite.JSON(), nullable=True))
        batch_op.create_index('idx_ai_result_type', ['result_type'], unique=False)
        batch_op.create_index('idx_ai_result_command', ['command_id'], unique=False)
        batch_op.drop_column('confidence')
        batch_op.drop_column('result_data')

    op.create_table('_alembic_tmp_ai_command_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('command_id', sa.INTEGER(), nullable=False),
    sa.Column('result_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('result_data', sqlite.JSON(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['ai_commands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
