"""add new table platform

Revision ID: e300de5e1f77
Revises: caf3e4fe81eb
Create Date: 2026-04-27 00:34:51.403204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e300de5e1f77'
down_revision = 'caf3e4fe81eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('duration_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_renewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.create_index('idx_sub_auto_renew', ['auto_renew'], unique=False)
        batch_op.create_index('idx_sub_created', ['created_at'], unique=False)
        batch_op.create_index('idx_sub_plan', ['plan_id'], unique=False)
        batch_op.create_index('idx_sub_plan_old', ['plan'], unique=False)
        batch_op.create_foreign_key("created_by", 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key("updated_by", 'users', ['updated_by'], ['id'])
        batch_op.create_foreign_key("plan_id", 'subscription_plans', ['plan_id'], ['plan_id'])
        batch_op.drop_column('plan_name_ar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_name_ar', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint("created_by", type_='foreignkey')
        batch_op.drop_constraint("updated_by", type_='foreignkey')
        batch_op.drop_constraint("plan_id", type_='foreignkey')
        batch_op.drop_index('idx_sub_plan_old')
        batch_op.drop_index('idx_sub_plan')
        batch_op.drop_index('idx_sub_created')
        batch_op.drop_index('idx_sub_auto_renew')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('last_renewed_at')
        batch_op.drop_column('cancelled_reason')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('duration_months')
        batch_op.drop_column('plan_id')

    
    # ### end Alembic commands ###
