"""add new columns for recource

Revision ID: f79962aab126
Revises: 916215142fa7
Create Date: 2026-03-20 23:36:13.556964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79962aab126'
down_revision = '916215142fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('specialization', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('experience_years', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('equipment_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('equipment_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('equipment_serial', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('manufacturing_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_schedule', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('material_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('material_grade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('material_specifications', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('reorder_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_maintenance', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('next_maintenance', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_cycle', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("supplier_id", 'users', ['supplier_id'], ['id'])
        batch_op.create_foreign_key("employee_id", 'users', ['employee_id'], ['id'])
        batch_op.create_foreign_key("creator_id", 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_constraint("supplier_id", type_='foreignkey')
        batch_op.drop_constraint("employee_id", type_='foreignkey')
        batch_op.drop_constraint("creator_id", type_='foreignkey')
        batch_op.drop_column('creator_id')
        batch_op.drop_column('is_available')
        batch_op.drop_column('maintenance_cycle')
        batch_op.drop_column('next_maintenance')
        batch_op.drop_column('last_maintenance')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('reorder_quantity')
        batch_op.drop_column('material_specifications')
        batch_op.drop_column('material_grade')
        batch_op.drop_column('material_type')
        batch_op.drop_column('maintenance_schedule')
        batch_op.drop_column('manufacturing_year')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('equipment_serial')
        batch_op.drop_column('equipment_model')
        batch_op.drop_column('equipment_type')
        batch_op.drop_column('experience_years')
        batch_op.drop_column('certifications')
        batch_op.drop_column('skills')
        batch_op.drop_column('specialization')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
